CREATE DATABASE IF NOT EXISTS pinfashion_ai CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE pinfashion_ai;

-- Use Prisma migrations in production. This handoff schema documents the MySQL tables, indexes and relationships.
CREATE TABLE users (id VARCHAR(191) NOT NULL PRIMARY KEY, name VARCHAR(191), email VARCHAR(191) UNIQUE, emailVerified DATETIME(3), image VARCHAR(191), createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL);
CREATE TABLE accounts (id VARCHAR(191) NOT NULL PRIMARY KEY, userId VARCHAR(191) NOT NULL, type VARCHAR(191) NOT NULL, provider VARCHAR(191) NOT NULL, providerAccountId VARCHAR(191) NOT NULL, refresh_token TEXT, access_token TEXT, expires_at INT, token_type VARCHAR(191), scope VARCHAR(191), id_token TEXT, session_state VARCHAR(191), UNIQUE KEY accounts_provider_account_unique(provider, providerAccountId), INDEX accounts_user_idx(userId), CONSTRAINT accounts_user_fk FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE sessions (id VARCHAR(191) NOT NULL PRIMARY KEY, sessionToken VARCHAR(191) NOT NULL UNIQUE, userId VARCHAR(191) NOT NULL, expires DATETIME(3) NOT NULL, INDEX sessions_user_idx(userId), CONSTRAINT sessions_user_fk FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE verification_tokens (identifier VARCHAR(191) NOT NULL, token VARCHAR(191) NOT NULL, expires DATETIME(3) NOT NULL, UNIQUE KEY verification_identifier_token_unique(identifier, token));
CREATE TABLE products (id VARCHAR(191) NOT NULL PRIMARY KEY, userId VARCHAR(191) NOT NULL, source ENUM('AMAZON','FLIPKART','MYNTRA','EARNKARO','OTHER') NOT NULL, sourceUrl TEXT NOT NULL, affiliateUrl TEXT, title VARCHAR(191) NOT NULL, brand VARCHAR(191), price DECIMAL(10,2), currency VARCHAR(191) DEFAULT 'INR', category VARCHAR(191), gender VARCHAR(191), fashionStyle VARCHAR(191), imageUrls JSON NOT NULL, metadata JSON, createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL, INDEX products_user_created_idx(userId, createdAt), INDEX products_source_idx(source), CONSTRAINT products_user_fk FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE generated_pins (id VARCHAR(191) NOT NULL PRIMARY KEY, userId VARCHAR(191) NOT NULL, productId VARCHAR(191), title VARCHAR(191) NOT NULL, description TEXT NOT NULL, tags JSON NOT NULL, boardSuggestion VARCHAR(191), status ENUM('DRAFT','GENERATED','SCHEDULED','PUBLISHED','FAILED') NOT NULL DEFAULT 'DRAFT', layout VARCHAR(191), scheduledFor DATETIME(3), publishedAt DATETIME(3), pinterestPinId VARCHAR(191), destinationUrl TEXT, createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL, INDEX generated_pins_user_status_idx(userId,status), INDEX generated_pins_product_idx(productId), CONSTRAINT generated_pins_user_fk FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT generated_pins_product_fk FOREIGN KEY(productId) REFERENCES products(id) ON DELETE SET NULL);
CREATE TABLE generated_images (id VARCHAR(191) NOT NULL PRIMARY KEY, generatedPinId VARCHAR(191) NOT NULL, prompt TEXT NOT NULL, cloudinaryUrl TEXT NOT NULL, publicId VARCHAR(191), width INT NOT NULL DEFAULT 1000, height INT NOT NULL DEFAULT 1500, layout VARCHAR(191), createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX generated_images_pin_idx(generatedPinId), CONSTRAINT generated_images_pin_fk FOREIGN KEY(generatedPinId) REFERENCES generated_pins(id) ON DELETE CASCADE);
CREATE TABLE pinterest_accounts (id VARCHAR(191) NOT NULL PRIMARY KEY, userId VARCHAR(191) NOT NULL, pinterestUserId VARCHAR(191) NOT NULL, username VARCHAR(191), encryptedAccess TEXT NOT NULL, encryptedRefresh TEXT, scopes VARCHAR(191), expiresAt DATETIME(3), createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL, UNIQUE KEY pinterest_accounts_user_remote_unique(userId,pinterestUserId), INDEX pinterest_accounts_user_idx(userId), CONSTRAINT pinterest_accounts_user_fk FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE boards (id VARCHAR(191) NOT NULL PRIMARY KEY, pinterestAccountId VARCHAR(191) NOT NULL, pinterestBoardId VARCHAR(191) NOT NULL, name VARCHAR(191) NOT NULL, description TEXT, privacy VARCHAR(191) NOT NULL DEFAULT 'PUBLIC', createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL, UNIQUE KEY boards_account_remote_unique(pinterestAccountId,pinterestBoardId), INDEX boards_account_idx(pinterestAccountId), CONSTRAINT boards_account_fk FOREIGN KEY(pinterestAccountId) REFERENCES pinterest_accounts(id) ON DELETE CASCADE);
CREATE TABLE scheduled_posts (id VARCHAR(191) NOT NULL PRIMARY KEY, userId VARCHAR(191) NOT NULL, generatedPinId VARCHAR(191) NOT NULL, pinterestAccountId VARCHAR(191) NOT NULL, boardId VARCHAR(191) NOT NULL, scheduledFor DATETIME(3) NOT NULL, status ENUM('DRAFT','GENERATED','SCHEDULED','PUBLISHED','FAILED') NOT NULL DEFAULT 'SCHEDULED', failureReason TEXT, jobId VARCHAR(191), createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL, INDEX scheduled_posts_user_time_idx(userId,scheduledFor), INDEX scheduled_posts_status_idx(status), CONSTRAINT scheduled_posts_user_fk FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT scheduled_posts_pin_fk FOREIGN KEY(generatedPinId) REFERENCES generated_pins(id) ON DELETE CASCADE, CONSTRAINT scheduled_posts_account_fk FOREIGN KEY(pinterestAccountId) REFERENCES pinterest_accounts(id) ON DELETE CASCADE, CONSTRAINT scheduled_posts_board_fk FOREIGN KEY(boardId) REFERENCES boards(id) ON DELETE CASCADE);
CREATE TABLE analytics (id VARCHAR(191) NOT NULL PRIMARY KEY, generatedPinId VARCHAR(191) NOT NULL, date DATETIME(3) NOT NULL, impressions INT NOT NULL DEFAULT 0, saves INT NOT NULL DEFAULT 0, clicks INT NOT NULL DEFAULT 0, outboundClicks INT NOT NULL DEFAULT 0, ctr DECIMAL(6,4) NOT NULL DEFAULT 0, createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), UNIQUE KEY analytics_pin_date_unique(generatedPinId,date), INDEX analytics_date_idx(date), CONSTRAINT analytics_pin_fk FOREIGN KEY(generatedPinId) REFERENCES generated_pins(id) ON DELETE CASCADE);
CREATE TABLE subscriptions (id VARCHAR(191) NOT NULL PRIMARY KEY, userId VARCHAR(191) NOT NULL, plan ENUM('FREE','CREATOR','AGENCY') NOT NULL DEFAULT 'FREE', status VARCHAR(191) NOT NULL DEFAULT 'active', providerCustomerId VARCHAR(191), providerSubId VARCHAR(191), currentPeriodEnd DATETIME(3), createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), updatedAt DATETIME(3) NOT NULL, INDEX subscriptions_user_status_idx(userId,status), CONSTRAINT subscriptions_user_fk FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE api_usage (id VARCHAR(191) NOT NULL PRIMARY KEY, userId VARCHAR(191) NOT NULL, route VARCHAR(191) NOT NULL, units INT NOT NULL DEFAULT 1, createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX api_usage_user_created_idx(userId,createdAt), INDEX api_usage_route_idx(route), CONSTRAINT api_usage_user_fk FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE);
CREATE TABLE outfit_recommendations (id VARCHAR(191) NOT NULL PRIMARY KEY, userId VARCHAR(191) NOT NULL, productId VARCHAR(191) NOT NULL, pants JSON NOT NULL, shoes JSON NOT NULL, accessories JSON NOT NULL, watches JSON NOT NULL, aesthetic VARCHAR(191) NOT NULL, rationale TEXT NOT NULL, createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3), INDEX outfit_user_created_idx(userId,createdAt), INDEX outfit_product_idx(productId), CONSTRAINT outfit_user_fk FOREIGN KEY(userId) REFERENCES users(id) ON DELETE CASCADE, CONSTRAINT outfit_product_fk FOREIGN KEY(productId) REFERENCES products(id) ON DELETE CASCADE);

